version: '3'
services:
#  db:
#    image: postgres:latest
#    container_name: postgresql
#    environment:
#      POSTGRES_DB: "${DB_DATABASE}"
#      POSTGRES_USER: "${DB_USERNAME}"
#      POSTGRES_PASSWORD: "${DB_PASSWORD}"
#    ports:
#      - "${DB_PORT}:${DB_PORT}"
  api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
#    depends_on:
#      - db